server:
  port: 8080
spring:
  application:
    name: user
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5432/users
    username: notiflow
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  security:
    oauth2:
      client:
        registration:
          google:
            client-secret:
            client-id:
            scope:
              - email
              - profile

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true