server:
  port: 8070

spring:
  application:
    name: telegram
  kafka:
    bootstrap-servers: localhost:29092
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5432/telegram
    username: notiflow
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    generate-ddl: true
    show-sql: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

telegram:
  bot-token: 6785621802:AAGQw0R5ooXba_xIWbPiesnn7OyX7aGEmB0