server:
  port: 8060

spring:
  application:
    name: email
  kafka:
    bootstrap-servers: localhost:39092

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true